defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: yo_development
  pool: 5
  username: postgres
  password:

development:
  <<: *defaults

test:
  <<: *defaults
  database: yo_test 

production:
  <<: *defaults
  database: yo_production
