language: ruby
env:
  matrix:
  - DISPLAY=:99.0
  global:
  - YO_HOME=/home/travis/build/mkhatib/yo-trial
  - secure: arVlbmxywQrWCUd9U5cO9lG+qZBXlD01fUG8U1w1DIjEFnaHzyYVEO4PWOWzLGmf2Vmv9OSvL3rhig8sibXaGvT+a1OksrLEApkk3wGvP2shTn8+8KCcEWhuhyZk5QQpfyWmMO4lGfZv1/iXZ9BcRceoEdF+jhpbQstLaL3Q7ZQ=
rvm:
- 1.9.3
before_install:
- cd /usr/lib/git-core/
- sudo wget https://raw.github.com/apenwarr/git-subtree/master/git-subtree.sh
- sudo mv git-subtree.sh git-subtree
- sudo chmod 755 git-subtree
- cd $YO_HOME/backend
- sudo apt-get update -qq
- sudo apt-get install -qq nodejs
before_script:
- cd $YO_HOME/backend
- psql -c 'create database yo_test;' -U postgres
- bundle exec rake db:migrate
- cd $YO_HOME/web-client
- npm install grunt --save-dev
- npm install
- sh -e /etc/init.d/xvfb start
- bower install
script:
- cd $YO_HOME/web-client && grunt test && cd $YO_HOME/backend && bundle exec rspec
after_success:
  - cd $YO_HOME
  - ./utils/travis/deploy.sh
