language: ruby
env:
  matrix:
  - DISPLAY=:99.0
  global:
    secure: arVlbmxywQrWCUd9U5cO9lG+qZBXlD01fUG8U1w1DIjEFnaHzyYVEO4PWOWzLGmf2Vmv9OSvL3rhig8sibXaGvT+a1OksrLEApkk3wGvP2shTn8+8KCcEWhuhyZk5QQpfyWmMO4lGfZv1/iXZ9BcRceoEdF+jhpbQstLaL3Q7ZQ=
rvm:
- 1.9.3
before_install:
- echo $TRAVIS_BRANCH
- pwd
- cd /usr/lib/git-core/
- sudo wget https://raw.github.com/apenwarr/git-subtree/master/git-subtree.sh
- sudo mv git-subtree.sh git-subtree
- sudo chmod 755 git-subtree
- cd /home/travis/build/mkhatib/yo-trial
- cd backend
- sudo apt-get update -qq
- sudo apt-get install -qq nodejs
before_script:
- psql -c 'create database yo_test;' -U postgres
- rake db:migrate
- cd ../web-client
- npm install grunt --save-dev
- npm install
- bower install
- sh -e /etc/init.d/xvfb start
script:
- cd ../web-client && grunt test
- cd ../backend && bundle exec rspec && bundle exec teaspoon
matrix:
  allow_failures:
  - rvm: jruby-19mode
  - rvm: ruby-head
after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]
  - then echo "Not master. No Deploy to do."; exit 0
  - else
  - echo "On master. Deploying now..."
  - cd /home/travis/build/mkhatib/yo-trial
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add web-client-heroku git@heroku.com:yo-trial-web-client.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git subtree push --prefix web-client/dist web-client-heroku master  
  - fi
