language: ruby
env:
  - DISPLAY=:99.0
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - "cd backend"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq nodejs"
before_script:
  - "psql -c 'create database yo_test;' -U postgres"
  - 'rake db:migrate'
  - "cd ../web-client"
  - 'npm install -g bower grunt-cli grunt'
  - 'npm install grunt --save-dev'
  - 'npm install'
  - 'sh -e /etc/init.d/xvfb start'
  - 'bower install'
script:
  - 'cd ../web-client && grunt test'
  - 'cd ../backend && bundle exec rspec && bundle exec teaspoon'
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
