language: ruby
env:
  - DISPLAY=:99.0
rvm:
  - 2.0.0
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq nodejs"
before_script:
  - "cd web-client"
  - 'npm install -g bower grunt-cli grunt'
  - 'npm install grunt --save-dev'
  - 'npm install'
  - 'bower install'
  - 'cd ../backend'
  - 'cp config/database.yml.sample config/database.yml'
  - "psql -c 'create database manshar_test;' -U postgres"
  - 'rake db:migrate'
  - 'npm install'
  - 'sh -e /etc/init.d/xvfb start'
script:
  - 'cd ../web-client && grunt test'
  - 'cd ../backend && bundle exec rspec && bundle exec teaspoon'
