language: ruby
rvm:
  - 2.0.0
before_install:
  - cd web-client
before_script:
  - 'npm install -g bower grunt-cli grunt'
  - 'npm install grunt --save-dev'
  - 'npm install'
  - 'bower install'
script:
  - grunt test
