language: ruby
env:
  matrix:
  - DISPLAY=:99.0
  global:
    secure: arVlbmxywQrWCUd9U5cO9lG+qZBXlD01fUG8U1w1DIjEFnaHzyYVEO4PWOWzLGmf2Vmv9OSvL3rhig8sibXaGvT+a1OksrLEApkk3wGvP2shTn8+8KCcEWhuhyZk5QQpfyWmMO4lGfZv1/iXZ9BcRceoEdF+jhpbQstLaL3Q7ZQ=
rvm:
- 1.9.3
- 2.0.0
- ruby-head
- jruby-19mode
jdk:
- oraclejdk7
- openjdk7
before_install:
- wget https://git-core.googlecode.com/files/git-1.8.5.1.tar.gz
- tar -zxf git-1.8.5.1.tar.gz
- cd git-1.8.5.1
- make prefix=/usr/local all
- sudo make prefix=/usr/local install
- sudo chmod +x /usr/share/doc/git/contrib/subtree/git-subtree.sh
- sudo ln -s /usr/share/doc/git/contrib/subtree/git-subtree.sh /usr/lib/git-core/git-subtree
- cd ../backend
- sudo apt-get install git-core
- sudo apt-get update -qq
- sudo apt-get install -qq nodejs
before_script:
- psql -c 'create database yo_test;' -U postgres
- rake db:migrate
- cd ../web-client
- npm install grunt --save-dev
- npm install
- bower install
- sh -e /etc/init.d/xvfb start
script:
- cd ../web-client && grunt test
- cd ../backend && bundle exec rspec && bundle exec teaspoon
matrix:
  allow_failures:
  - rvm: jruby-19mode
  - rvm: ruby-head
after_success:
  - git --version
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add web-client-heroku git@heroku.com:yo-trial-web-client.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git subtree push --prefix web-client/dist web-client-heroku master
